### ISSUE TITLE
"Rate Limit Exceeded" issue

### ISSUE THREAD

**Issue by RakshitThakker** [divsbhalala/Twittery#1]
While I was testing, I was frequently getting this page -- http://twittery-rttweet.rhcloud.com/home.php/clearsession.php?error=Rate%20limit%20exceeded and then it shows "rate limit exceeded" error. Please check attached file.

I do understand that every API has a limit, but you have find out way to optimise your code and implement some mechanism so that your application don't hit rate limit.
![twitter-rate-limit](https://cloud.githubusercontent.com/assets/1140038/8028786/af8af6f4-0dd1-11e5-9e2e-57e0e8e557f9.png)

**Comment by divsbhalala** [comment]
i have try to optimise the rate limit error for twittery app but  some time throw error because of twitter sets a limit on how many times it can be used in an hour
