### ISSUE TITLE
9 tweets are displayed instead of 10

### ISSUE THREAD

**Issue by RakshitThakker** [divsbhalala/Twittery#2]
`10 tweets will be displayed using a jQuery-slideshow.` ( Ref: https://rtcamp.com/careers/web-developers/assignments/ )

Only 9 tweets are displayed in slideshow

**Comment by divsbhalala** [comment]
i was counted. its show me 10 tweets every in slideshow

**Comment by RakshitThakker** [comment]
Please check again

**Comment by RakshitThakker** [comment]
You can verify with this XML file -- http://twittery-rttweet.rhcloud.com/download/rt_test1.xml

It has `<tweet_0>` to `<tweet_8>`

**Comment by divsbhalala** [comment]
i was check again in two diffrent account its shows me 10 tweet every time

please check here xml file-- 
 http://twittery-rttweet.rhcloud.com/download/Dsbhalala99.xml
http://twittery-rttweet.rhcloud.com/download/Nakranihardik.xml

also see the bellow image it show 10 tweet in xml
![screenshot from 2015-06-10 08 12 49](https://cloud.githubusercontent.com/assets/12185309/8073880/9f3da79c-0f48-11e5-98ca-a55dd9f6028a.png)

**Comment by RakshitThakker** [comment]
Fine.
