### ISSUE TITLE
Download Tweets

### ISSUE THREAD

**Issue by RakshitThakker** [divsbhalala/Twittery#3]
`There will be a download button to download all tweets for logged in user.` ( Ref: https://rtcamp.com/careers/web-developers/assignments/ )

Looks like you missed above point from assignment.

**Comment by divsbhalala** [comment]
i make download button for login user tweet with their follower tweet for downloading with limit 10.
i have 1 question.
can put download button for  login users to download all tweet not for followers tweet?

**Comment by RakshitThakker** [comment]
Download button should give me file containing my tweets (and not tweets of people I follow)

**Comment by divsbhalala** [comment]
i did download button to download tweet only for login user

**Comment by RakshitThakker** [comment]
CSV and XML are showing only 200 tweets.

**Comment by RakshitThakker** [comment]
Even Excel export is showing only 200 tweets.

Moreover, for excel export, column "id_str" has some issue.

![excel-id_str-issue](https://cloud.githubusercontent.com/assets/1140038/8106786/09590db4-1062-11e5-9d30-e5f15865bd49.png)

**Comment by divsbhalala** [comment]
i have remove  the single quotes(&apos;) and get only 200 tweets just because twitter give up to a maximum of 200 tweet per request

**Comment by RakshitThakker** [comment]
You should enhance your code and try to get all the tweets

On Thursday, June 11, 2015, divyesh bhalala notifications@github.com
wrote:

> i have remove the single quotes(') and get only 200 tweets just because
> twitter give up to a maximum of 200 tweet per request
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/divsbhalala/Twittery/issues/3#issuecomment-111205610.

## 

Rakshit Thakker | Project Manager
rtCamp Solutions Pvt. Ltd. | https://rtcamp.com/

**Comment by divsbhalala** [comment]
i have enhance and now download more then 200 tweet 

please check below image 
![screenshot from 2015-06-11 23 00 29](https://cloud.githubusercontent.com/assets/12185309/8113775/d718cda4-108d-11e5-9b27-d0e760d71c53.png)
