### ISSUE TITLE
Downloading CSV and other files on system

### ISSUE THREAD

**Issue by RakshitThakker** [divsbhalala/Twittery#4]
CSV, JSON and XML files are opening in browser instead of downloading on system

**Comment by divsbhalala** [comment]
i was cheked its downloging in my system not opening in browser
![screenshot from 2015-06-10 07 48 30](https://cloud.githubusercontent.com/assets/12185309/8073637/70e76408-0f45-11e5-9160-5eb4b9143db4.png)

please see below the image for downloading on system xml,json,xls,json file
![screenshot from 2015-06-10 07 47 55](https://cloud.githubusercontent.com/assets/12185309/8073645/80e70a20-0f45-11e5-98a4-fc42369c8480.png)

**Comment by RakshitThakker** [comment]
It's not working with Safari.

**Comment by divsbhalala** [comment]
now work in safari please check
