### ISSUE TITLE
Followers search don't work

### ISSUE THREAD

**Issue by RakshitThakker** [divsbhalala/Twittery#5]
I have more than 100+ followers and search don't work properly.

I guess your code searches from last 50 followers only.

`$friend_list = $twitteroauth->get("https://api.twitter.com/1.1/followers/list.json?cursor=-1&screen_name=" . $user_info->screen_name . "&skip_status=true&include_user_entities=false&count=50");`

Your code should not put any kind of limit when a search is performed and should query all the followers.

**Comment by divsbhalala** [comment]
i did search for all followers please check it
