### ISSUE TITLE
Add your code to Scrutinizer and enhance it by eliminating bugs and improving code quality

### ISSUE THREAD

**Issue by RakshitThakker** [divsbhalala/Twittery#7]
Head to scrutinizer-ci.com and add, verify and improve your assignment code.

**Comment by divsbhalala** [comment]
i was already check my code at scrutinizer-ci.com

approx 9.3 to entire git repository and 
approx 8.34 after excluding  lib,test and download directory

**Comment by RakshitThakker** [comment]
Please check https://scrutinizer-ci.com/g/divsbhalala/Twittery/issues/master

**Comment by divsbhalala** [comment]
i have try to improve code quality 8.34 to approx 9.36  given by the  scrutinizer-ci.com

**Comment by RakshitThakker** [comment]
Fix this --> https://scrutinizer-ci.com/g/divsbhalala/Twittery/indices/915075/duplications/73516255

**Comment by divsbhalala** [comment]
i had fix above issue

**Comment by RakshitThakker** [comment]
I still see some code duplication.

Please check --> https://scrutinizer-ci.com/g/divsbhalala/Twittery/issues/master?selectedLabels%5B0%5D=4&orderField=path&order=asc

**Comment by divsbhalala** [comment]
now i had removed all duplicate code as possible as
